### ISSUE TITLE
Dropping the Required Sign In

### ISSUE THREAD

**Issue by CooperWhitlow** [OneDrive/onedrive-explorer-js#3]
Is there anything in the works to allow guests to use this explorer without sign in (via a guest link)?

**Comment by daspek** [comment]
Nothing in the works... are you asking because you don't have a OneDrive account, or because you want to avoid letting the explorer sample view your OneDrive?

**Comment by CooperWhitlow** [comment]
We already use a OneDrive to store photos. I'm just looking for a solution to allow the general public to view and explore photos on our account without needing our sign in credentials to do so.

**Comment by rgregg** [comment]
I think what you're asking for is a way to use the OneDrive API with sharing links anonymously, which is a little different than wanting to using the javascript explorer anonymously. We're looking into how we can enable the API to be used with sharing links but don't have an ETA right now.

**Comment by CooperWhitlow** [comment]
@rgregg indeed, shared 'view' links. Glad to hear this might be supported in the future and allow our organization to use OneDrive.
