### ISSUE TITLE
use different domain return url in OneDrive Filepicker

### ISSUE THREAD

**Issue by luolan519** [OneDrive/onedrive-explorer-js#4]
Our company wants to integrate One Drive for business in our application. Our goal is using OneDrive filepicker to download files from One Drive business account to our server. Form the One Drive for business App documentation, for filepicker, the return url must be the same domain as the request page. Our scenario is our server hosts a lot of customers and each customer has their own domains.  We try to find a solution which multiple domains filepicker can share the same return url. Is it possible?

**Comment by daboxu** [comment]
Hi @luolan519, which version of the picker you are trying to use? For v7.0 I think it is possible to config different return url in your app.

**Comment by luolan519** [comment]
Good morning Dabo,

Thanks for replying my email so quickly. We are using  v7.0 picker and what we try to do is using cross domain return url in our app.

Domain one: https://localdevnet.intrafinity.com/

Domain two: https://localstaging.intrafinity.com/

we use picker in Domain one and return url is "https://localstaging.intrafinity.com/test/onedirvefilepickercallback.aspx". When we use picker, it can open Onedrive for business account and display all the items we have, but when we try to open an item, the popup window didn't close and threw error ( see attachment ).

Please advice and thanks for advance,

Lan

**Comment by daboxu** [comment]
Hi Lan, I have not seen the attachment. Could you please kindly sent it direct to dabxu@microsoft.com? If you could attach the fiddler trace, that would be wonderful.

**Comment by daboxu** [comment]
And for the different domain, right now the failure is expected because it is a prerequisite for using the picker.

**Comment by daboxu** [comment]
Close this thread because synced with @luolan519 via email and the feature redirecting to different domain is not implemented in JS Picker v7.0.
