### ISSUE TITLE
UnauthorizedAccessException when using my app on different tenant

### ISSUE THREAD

**Issue by niesink** [OneDrive/onedrive-explorer-js#5]
In my webapp I've used the Onedrive JS API, as described here: https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm to allow my users to pick a file (from which the url is then sent to my webapp). For this I've registered an app as described on that same page.

This works fine with my own Onedrive Business account and colleagues on the same (Azure) tenant.

But when a customer of ours tries to use it on their account the `OneDrive.js` throws this error: `[OneDriveSDK] calling xhr failure callback, status: 401`
followed by this reponse:
(the Dutch loosely translates to: "Access Denied. You are not authorised to perform this action or open this resource")

```
"{
  "error": {
    "code": "-2147024891, System.UnauthorizedAccessException",
    "message": "Toegang geweigerd. U bent niet gemachtigd om deze bewerking uit te voeren of deze bron te openen.",
    "innerError": {
      "request-id": "81c39bae-5004-4657-b7a5-1e06a35da730",
      "date": "2016-07-18T10:25:38"
    }
  }
}"
```

Is there something I have to enable on my side to allow the customer to use my app or does the customer have to enable something on their side?

**Comment by rgregg** [comment]
@niesink: Can you check the "multi-tenant" state of your application in Azure AD? For other tenants to be able to sign into your application you need to have the multi-tenant setting set to Yes.

<img width="387" alt="screen shot 2016-07-18 at 10 04 56 am" src="https://cloud.githubusercontent.com/assets/1435771/16923470/4e655d7c-4ccf-11e6-979c-4adb15eab0a6.png">

**Comment by niesink** [comment]
@rgregg thanks, where can I check this? I registered my app through https://apps.dev.microsoft.com and I don't see a multi-tenant setting there.

EDIT: To clarify I used that page to register my app because that is what https://dev.onedrive.com/sdk/js-v7/js-picker-open.htm told me to do :) I believe this means I'm using the V2 API, right? Am I correct in thinking that the switch you are referring to only applies to V1 API apps, which are managed through https://manage.windowsazure.com? Is there a similar switch for my kind of app (using the V2 API)?

**Comment by niesink** [comment]
@rgregg Is there a different 'channel' I can turn to with my question? All other roads seem to lead to Office365 (end-user) Support, who don't appear to be able to help me with this issue.

**Comment by rgregg** [comment]
If you still need help here, a) I'm sorry, and b) please let me know.

**Comment by niesink** [comment]
@rgregg I'm afraid we're still having trouble with this, recently I've opened the following issue, though unfortunately @daboxu has gone quiet :(

https://github.com/OneDrive/onedrive-api-docs/issues/499#issuecomment-271928163

Maybe you can be of assistance?
